'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings 自動保存機能"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property 各座席ボタンのID() As String
            Get
                Return CType(Me("各座席ボタンのID"),String)
            End Get
            Set
                Me("各座席ボタンのID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property 各座席ボタンのX座標() As String
            Get
                Return CType(Me("各座席ボタンのX座標"),String)
            End Get
            Set
                Me("各座席ボタンのX座標") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property 各座席ボタンのY座標() As String
            Get
                Return CType(Me("各座席ボタンのY座標"),String)
            End Get
            Set
                Me("各座席ボタンのY座標") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property 各座席ボタンのテキスト() As String
            Get
                Return CType(Me("各座席ボタンのテキスト"),String)
            End Get
            Set
                Me("各座席ボタンのテキスト") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property 各座席ボタンの数() As Integer
            Get
                Return CType(Me("各座席ボタンの数"),Integer)
            End Get
            Set
                Me("各座席ボタンの数") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property 各座席ボタンの高さ() As Integer
            Get
                Return CType(Me("各座席ボタンの高さ"),Integer)
            End Get
            Set
                Me("各座席ボタンの高さ") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("110")>  _
        Public Property 各座席ボタンの幅() As Integer
            Get
                Return CType(Me("各座席ボタンの幅"),Integer)
            End Get
            Set
                Me("各座席ボタンの幅") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
        Public Property 各座席ボタンのフォントサイズ() As String
            Get
                Return CType(Me("各座席ボタンのフォントサイズ"),String)
            End Get
            Set
                Me("各座席ボタンのフォントサイズ") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("bb4842f5-9956-44eb-8a0d-d7801c685c06")>  _
        Public Property irucaのルームコード() As String
            Get
                Return CType(Me("irucaのルームコード"),String)
            End Get
            Set
                Me("irucaのルームコード") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property 離席になるまでの時間() As Integer
            Get
                Return CType(Me("離席になるまでの時間"),Integer)
            End Get
            Set
                Me("離席になるまでの時間") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("未設定")>  _
        Public Property 離席判定対象のID() As String
            Get
                Return CType(Me("離席判定対象のID"),String)
            End Get
            Set
                Me("離席判定対象のID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property 離席判定をするかどうか() As Boolean
            Get
                Return CType(Me("離席判定をするかどうか"),Boolean)
            End Get
            Set
                Me("離席判定をするかどうか") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("""""")>  _
        Public Property 離席判定対象の名前() As String
            Get
                Return CType(Me("離席判定対象の名前"),String)
            End Get
            Set
                Me("離席判定対象の名前") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property vanilla() As Boolean
            Get
                Return CType(Me("vanilla"),Boolean)
            End Get
            Set
                Me("vanilla") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ウィンドウのX座標() As Integer
            Get
                Return CType(Me("ウィンドウのX座標"),Integer)
            End Get
            Set
                Me("ウィンドウのX座標") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ウィンドウのY座標() As Integer
            Get
                Return CType(Me("ウィンドウのY座標"),Integer)
            End Get
            Set
                Me("ウィンドウのY座標") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ウィンドウの幅() As Integer
            Get
                Return CType(Me("ウィンドウの幅"),Integer)
            End Get
            Set
                Me("ウィンドウの幅") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ウィンドウの高さ() As Integer
            Get
                Return CType(Me("ウィンドウの高さ"),Integer)
            End Get
            Set
                Me("ウィンドウの高さ") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property 自動起動() As Boolean
            Get
                Return CType(Me("自動起動"),Boolean)
            End Get
            Set
                Me("自動起動") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property 自動更新をするかどうか() As Boolean
            Get
                Return CType(Me("自動更新をするかどうか"),Boolean)
            End Get
            Set
                Me("自動更新をするかどうか") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property 自動更新間隔() As Integer
            Get
                Return CType(Me("自動更新間隔"),Integer)
            End Get
            Set
                Me("自動更新間隔") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ZaisekiKakunin.My.MySettings
            Get
                Return Global.ZaisekiKakunin.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
